formats:
  - oas2
  - oas3

rules:
  validation-api:
    description: sample async function
    message: '{{error}}'
    given: $.paths..responses..schema..properties[*]~
    recommended: true
    type: style
    severity: error
    then:
      function: validateProperties
functions:
  - validateProperties
