formats:
  - oas3
  - oas2
extends:
  - 'spectral:oas'
rules:
  info-matches-stoplight:
    description: This is an example rule
    message: Info must contain Stoplight
    given: $.info
    recommended: true
    type: style
    then:
      field: title
      function: pattern
      functionOptions:
        match: Stoplight
  validateProperties:
    message: '{{error}}'
    severity: error
    given: '$.paths...*.schema..properties'
    then:
      function: validateProperties
functions:
  - validateProperties
