formats:
  - oas2
  - oas3
extends:
  - 'spectral:oas'
rules:
  info-matches-stoplight:
    description: This is an example rule
    message: Info must contain Stoplight
    given: $.info
    recommended: true
    type: style
    then:
      field: title
      function: pattern
      functionOptions:
        match: Stoplight

  validation-api:
    description: test
    message: 'invalid field {{error}}'
    given: $.paths..responses..schema..properties[*]~
    recommended: true
    type: style
    severity: error
    then:
      function:
