formats:
  - oas3
  - oas2
rules:
  validateProperties:
    description: sample async function
    message: '{{error}}'
    severity: error
    given: '$.paths...*.schema..properties'
    then:
      function: validateProperties
functions:
  - validateProperties
